test

diff --git a/27-test b/27-test
--- a/27-test
+++ b/27-test
@@ -4,6 +4,11 @@ SOURCE_DIR=$1
 DEST_DIR=$2
 DAYS=${3:-14} # if user is not providing number of days, we are taking 14 days as default;
 
+USAGE(){
+   echo -e "$R ERROR:: $N sh 18-backup.sh <SOURCE_DIR> <DEST_DIR> <DAYS(optional)>"
+   exit 1
+}
+
 if [ $# -lt 2 ]
     then 
          USAGE # $ is not given infront of USAGE, because it is function
